setup:
	make -C debug setup
	make -C json setup
	make -C view setup
	make -C eval setup
	make -C check setup

build:
	make -C debug build
	make -C json build
	make -C view build
	make -C eval build
	make -C check build

.PHONY: build
