setup:
	make -C debug setup
	make -C json setup
	make -C view setup
	make -C eval setup
	make -C check setup

build:
	make -C debug build
	make -C json build
	make -C view build
	make -C eval build
	make -C check build

clean:
	make -C debug clean
	make -C json clean
	make -C view clean
	make -C eval clean
	make -C check clean

.PHONY: setup build clean
