title = "SysDC"
theme = "lynx"
copyright = "©2022 Yuta NAKAGAMI"

languageCode = "ja-JP"
defaultContentLanguage = "ja"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params]
title = "SysDC"
description = "SysDC トップページ"
images = ["sysdc-ogp.png"]

[author]
    name = "SysDC"
    headline = "SysDCはソフトウェア設計の支援を目的とする言語です"
    image = "icon.png"
    links = [
        { web-editor = { href = "/editor", text = "オンラインエディタ", icon = "web-editor" } },
        { doc = { href = "/doc", text = "ドキュメント", icon = "doc" } },
        { github = { href = "https://github.com/Yuta1004/SysDC", text = "Github" } },
        { sechack365 = { href = "https://sechack365.nict.go.jp/", text = "SecHack365", icon = "sechack365" } }
    ]
