version: "3"

services:
  proxy:
    image: envoyproxy/envoy:v1.24.0
    ports:
    - ${SYSDC_PORT}:50000
    volumes:
    - type: bind
      source: "./proxy/envoy.yaml"
      target: "/etc/envoy/envoy.yaml"
      read_only: true
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - top
      - doc
      - editor-front
      - editor-back
      - tool-delivery
      - storage

  top:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server --disableLiveReload --baseURL=${SYSDC_BASE_URL} --appendPort=false
    volumes:
    - type: bind
      source: "./top"
      target: "/src"
    environment:
      TZ: Asia/Tokyo

  doc:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server --disableLiveReload --baseURL=${SYSDC_BASE_URL}/doc --appendPort=false
    volumes:
    - type: bind
      source: "./doc"
      target: "/src"
    environment:
      TZ: Asia/Tokyo

  editor-front:
    build: ./editor/front
    image: sysdc/server/editor-front:run
    environment:
      TZ: Asia/Tokyo

  editor-back:
    build: ./editor/back
    image: sysdc/server/editor-back:run
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpass
      AWS_REGION: ap-northeast-1

  tool-delivery:
    build: ./tool/delivery
    image: sysdc/server/tool-delivery:run
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpass
      AWS_REGION: ap-northeast-1

  storage:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z.fips
    command: server --console-address ":9001" /data
    ports:
    - 9001:9001
    environment:
      TZ: Asia/Tokyo
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpass
    volumes:
    - type: volume
      source: storage-v
      target: "/data"

volumes:
  storage-v:
    driver: local
